### PR TITLE
Ports exploration drones from tg! [PORT FROM TG]

### PR DESCRIPTION
**Pull request by bruhlookatthisdood**
## Exploration Drones
A new side-job for cargo. Prepare and launch exploration drones at distant sites to encounter weird adventures, collect loot and expand the station cargo network. Adventures - the main content type here, can be written by anyone without any knowledge of programming. The purpose here is creating an way of interesting way of delivering lore (and adding some new job content/cargo expansion method).

### Scanning
First step to exploring is finding a place to explore, that's where the scanner arrays come in.
Build scanner arrays then choose scan types to either find anomalous sites or scan them more deeply for information on present dangers and opportunities. Building more arrays will improve scan times for far away sites. Some sites are affected by scan conditions which require specific placement of the scan arrays, information from scanning these types of sites is useful for new type of experiment.

### Drones & Launching
After locating a site, equip the drone with tools appropriate for what you know of the target (or just go blind) but remember that drones have limited cargo storage shared between tools and loot. Any loot found while cargo is full will be forever lost.
Launching drones requires fuel that can be created in the atmospheric crystallizer.
Better quality fuel shortens drone travel times.
Load up the fuel into the drone launcher and you're ready to start exploration
image

### Adventures
Text adventures are stored in config as JSON files for suspense and easy creation of new ones.
image

### Creating new adventures
Yes YOU can even create a new adventure! A online editor is available at https://anturk.github.io/adventure-maker/ (source here)
The JSON provided by the editor is ready to go adventure. I'll be trying to set up some automated process for adding these on our servers later on.

## Changelog
🆑
add: Adds exploration drones from TG! Read PR #479  for more information.
/🆑

### CODE REVIEW

**Review by BlackCat-055 — DISMISSED** [review]
These are all the errors I could find. please fix them. These aren't from your changed files, these are simply outdated due to the merging of the Modular Tegu file into bungalow. Most of these are just incorrect and needs updating but some work may be needed for the static type proc calls. Those are warnings though so while not game breaking, may be check failing still

image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image

image


image


image

**Comment by bruhlookatthisdood** [comment]
Thats... a feature.

**Comment by bruhlookatthisdood** [comment]
ive awaken from my slumber

**Comment by bruhlookatthisdood** [comment]
its fixed, halelughia!

**Comment by bruhlookatthisdood** [comment]
pretty much ready for a merge except that there is no map areas for it on box or fermi ( i think )
i just cant find a good place for it on box without stuffing it in maints.

**Comment by Kitsunemitsu** [comment]
We can do map things on fermi later, there is a room already set up for it.

Approving, need another dev to merge.

**Pull request merged**
