### PR TITLE
[WIP] Due to me being consumed by absolute insanity: Body Pillows

### PR DESCRIPTION
**Pull request by SqueezyS**
## About The Pull Request

YOU HAVE NO IDEA HOW READY YOU ARE

A BUNCH OF SS13 THEMED BODY PILLOWS
A FEW FACTS
-SEVENTEEN PEOPLE HAVE ALREADY DIED
-I AM GOING TO GO TO HELL
-THIS WILL ADD AROUND SIX OR MORE BODY PILLOWS
-I GET ZERO BITCHES

## Why It's Good For The Game

It isn't, it is not about the pull request itself. It's about sending a message. A message that ever man, woman, and child should never have to understand. 

Just kidding. Just imagine yourself finding one of these and thinking, "Wow, I never expected this"

## Changelog
:cl:
add: Adds body pillows
imageadd: Adds body pillow dmis
/:cl:

### CODE REVIEW

**Comment by thevandie** [comment]
NO-

**Comment by Honkers-the-clown** [comment]
further proof that you are indeed, maidenless

**Review by EgorDinamit — CHANGES_REQUESTED** [review]
Make actual code & icons.

**Comment by Kitsunemitsu** [comment]
Can't wait until this is ready to merge, I will make a body pillow a bubblegum reward

**Comment by SqueezyS** [comment]
> Can't wait until this is ready to merge, I will make a body pillow a bubblegum reward

Amazing

**Comment by bruhlookatthisdood** [comment]
no

**Comment by SqueezyS** [comment]
yes

**Comment by SqueezyS** [comment]
I cannot physically handle this anymore

**Pull request closed without merging**
