### PR TITLE
Changing L504

### PR DESCRIPTION
**Pull request by thevandie**
## About The Pull Request

Adds 3 new sprites for the L504 guns, one for the naga, one for the normal l504, and a completely new one for the small L504. Also made sure the naga had its nice glowy bayonet on the sprite. Based on the ones Netta made but with some adjustments. Oh yeah, the barrel dot grows dark once it runs out of ammo on all 3. Tested on local, worked just fine.

## Why It's Good For The Game

These sprites are closer to the original older lasgun as the whole point of these when they were added in the first place was to be close to the originals.

## Changelog
:cl:
add: new sprite for the L504 Lasgun and small L504 Lasgun
add: new sprite for the Cybersun Naga Lasgun
/:cl:

l504
l504small
naga

### CODE REVIEW

**Comment by thevandie** [comment]
wait one sec, i gotta make a small change

**Comment by retlaw34** [comment]
That shading on the front of the gun is pretty horrifying. The random red pixel doesn't fit well with the rest,

**Comment by thevandie** [comment]
Well, I asked a bunch of people. Total that's 6:1 for the current gun being fine, so I see no issues.

**Review by EgorDinamit — CHANGES_REQUESTED** [review]
Simple PR that changes item descriptions and icons.
Should be good to merge.

**Pull request merged**
