### PR TITLE
makes the nanotrasen meeting area ( i think that is it's name ) be a heart

### PR DESCRIPTION
**Pull request by bruhlookatthisdood**
## About The Pull Request

title
image

## Why It's Good For The Game

❤️ 

## Changelog
:cl:
add: Added a heart to the nanotrasen meeting area
/:cl:

### CODE REVIEW

**Comment by DaddyIssues98** [comment]
imagen?

**Comment by thevandie** [comment]
the mechs still need replaced with the showroom ones, may as well do it?

**Comment by bruhlookatthisdood** [comment]
> the mechs still need replaced with the showroom ones, may as well do it?

we dont have showcase seraphs

**Comment by Kitsunemitsu** [comment]
Don't use seraphs then <#

**Comment by bruhlookatthisdood** [comment]
> Don't use seraphs then <#

done

**Comment by DaddyIssues98** [comment]
big dick energy room

**Pull request merged**
