### PR TITLE
Punishing bird

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About The Pull Request

Adds a punishing bird, fun little bird that will annoy people at random. Do not attack it, or else...

## Why It's Good For The Game

First bird out of three. When I will assemble all of them, something truly epic should happen.

## Changelog
:cl:
add: Punishing bird. Do not attack it if you find one.
/:cl:

### CODE REVIEW

**Comment by EgorDinamit** [comment]
Sprites made by me. If there's anyone willing to upgrade them - be my guest.

**Comment by BlackCat-055** [comment]
> Sprites made by me. If there's anyone willing to upgrade them - be my guest.

Noted, lemme see if I can do something

**Comment by Kitsunemitsu** [comment]
Egor said this is good so we're good to go.

**Comment by thevandie** [comment]
jeez, that took a while to port

**Pull request merged**
