### PR TITLE
[MDB IGNORE] [IDB IGNORE] Baytiles/ bruteforces the shit out of tgui

### PR DESCRIPTION
**Pull request by retlaw34**
## About The Pull Request
@Kitsunemitsu

## Changelog
:cl:
add: baytiles
add: Updates TGUI.
/:cl:

### CODE REVIEW

**Comment by thevandie** [comment]
sus

**Comment by bruhlookatthisdood** [comment]
image
wowwies

**Comment by Kitsunemitsu** [comment]
I'll fix this in a bit.... still need to get my code commissions done

**Comment by thevandie** [comment]
wait, is this adding the bay tile sprites, or do bay tiles work in a unique way?

**Comment by retlaw34** [comment]
yes this replaces the ICONIC and CLASSIC sprites that floor tiles have
though, its up to a mapper to use them to its full potential

**Pull request closed without merging**
