### PR TITLE
 Kepler Map Update Part 3.5B. Huge Content!

### PR DESCRIPTION
**Pull request by projectkepler-ru**
## About The Pull Request
 I quickly fixed issues we had with some of the road being gen turf and updated some more stuff

## Why It's Good For The Game
immersion, making the game 'better'

on V4 update We will hopefully get the ranger in + the super outpost (should be done in a month, this area is huge)
Adding in a lot of stuff
After this I want to begin development on the desert and jungle planet when I have time.
## Changelog
:cl:

fix: fixed the road gen turf being incorrectly labeled
tweaks: made it so that defeating the boss of the facility drop slightly more stuff
tweaks: changed the mauler mech, slightly.
add: more ranger clothings
add: Kepler Uzi (fit in bag)
add: generic kepler clothings and cloak
imageadd: icons for uzi, ranger, generic kepler clothings, ranger cloak
add: lights where there are missing lights. 
add: a mech garage that SHOULD now start with some mech parts for you to start your own mech in sol gov.
add: some mech part onto secure storage 2 
/:cl:

### CODE REVIEW

**Comment by projectkepler-ru** [comment]
I've no idea why the linter check failed.

**Comment by projectkepler-ru** [comment]
somethings wrong again.

**Comment by projectkepler-ru** [comment]
fuck my life i guess

**Comment by Kitsunemitsu** [comment]
Ok now that the bugs are all fixed I will be looking at the code finally

**Comment by Kitsunemitsu** [comment]
I will have to modularize this soon, I will do today or tomorrow

**Comment by Kitsunemitsu** [comment]
Merging, should be good to go for now.

**Pull request merged**
