### PR TITLE
Removes the "Dizzy" symptom from virology

### PR DESCRIPTION
**Pull request by BootlegBow**
## About The Pull Request

Removes the symptom.
Dizziness as a mechanic still exists, but has no dedicated virology symptom.

## Why It's Good For The Game

- It's never used by anyone other than shitty viros and griefers
- Some players might get headaches/other issues from it
- It shakes your screen for no good fucking reason, whose idea was this?

## Changelog
:cl:
del: dizziness symptom from viro
/:cl:

### CODE REVIEW

**Comment by Kitsunemitsu** [comment]
Jones I just want to bring up that the screenshake is a side effect iirc.

The main effect is making you wake around randomly

**Comment by Kitsunemitsu** [comment]
I'll review in the morning, I'm going to bed

**Comment by BootlegBow** [comment]
randomly walking around is a seperate symptom called confusion

**Comment by Kitsunemitsu** [comment]
I'm holding it to you to make a new Viro symptom before any further Viro PRs go through

**Comment by bruhlookatthisdood** [comment]
> 

the one that makes you give birth to bees.
but now its hostile jones plushies

**Comment by BootlegBow** [comment]
> I'm holding it to you to make a new Viro symptom before any further Viro PRs go through
@Kitsunemitsu 
hold it to deez nuts

**Pull request merged**
