### PR TITLE
Overmap

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
For Jones to work on

### CODE REVIEW

**Comment by bruhlookatthisdood** [comment]
w h a t
what is an overmap

**Comment by Lyn505** [comment]
> w h a t what is an overmap

https://github.com/Skyrat-SS13/Skyrat-tg/pull/7982 Skyrat has already tried to port it, and failed miserably.

**Review by retlaw34 — APPROVED** [review]
Sprites are fine, as for code, i would have to look more in depth

**Comment by Kitsunemitsu** [comment]
Wasn't edited by jones who said they would edit it. Sadge.

**Pull request closed without merging**
