### PR TITLE
(Maybe) Kills the 2 hour shift limit

### PR DESCRIPTION
**Pull request by BootlegBow**
## About The Pull Request

Title

## Why It's Good For The Game

Literally everyone hates it

## Changelog
:cl:
del: 2hr shift limit
/:cl:

### CODE REVIEW

**Comment by BootlegBow** [comment]
FUCK

**Comment by JohnFulpWillard** [comment]
TGS don't actually update to what the codebase has so you need to change it there instead, in the config file.

**Comment by thevandie** [comment]
config got changed or something so it might actually work idk

**Comment by Kitsunemitsu** [comment]
I fixed it

**Comment by Kitsunemitsu** [comment]
I fixed it.
Still should probably TM

**Comment by SqueezyS** [comment]
Based.

**Review by retlaw34 — APPROVED** [review]
Oops

**Comment by retlaw34** [comment]
Actually, can you set this to something extremely long like 6 or 8 hours? At that point server needs to restart so issues don't crop up

**Comment by Kitsunemitsu** [comment]
I second Retlaw. Having it be very obscenely long is better than it not ending at all, potentially.

**Review by Kitsunemitsu — CHANGES_REQUESTED** [review]
Make it like 6 or 8 hrs, the server needs to rest.

**Comment by Kitsunemitsu** [comment]
Jones is fucking dead, I'm gonna fix and merge

**Review by Kitsunemitsu — APPROVED** [review]

**Pull request merged**
