### PR TITLE
Minor Uniform Related Improvements

### PR DESCRIPTION
**Pull request by thevandie**
## About The Pull Request

This includes a lot of Misc changes and additions. Some of these include, new sec formal jacket sprites, a proper unique outfit for military police, a unique outfit for the secoff senior title, most instances of brown sneakers with laceups or otherwise, and adds tan jackets for security. 

Has been tested on local. Worked.

Jacket:
jacket

## Why It's Good For The Game

All of these minor additions help improve the game. More unique outfits for alt titles helps differentiate them, updating the formal jacket sprites is probably a good idea since we already got their equivalent uniform sprites, and I fucking hate brown sneakers.

## Changelog
:cl:
add: new security formal jacket sprites
add: proper outfit for NTMP (alt title)
add: rename NTMP (alt title) to Reserve MP
add: outfit for Sergeant Officer (Secoff senior title)
add: replaces almost every use of brown sneakers by default and replaces them with laceups (except for CE and CMO, CE gets workboots and CMO gets white sneakers), QM is the one exception as it actually works for him.
/:cl:

### CODE REVIEW

**Comment by EgorDinamit** [comment]
Why are those empty?
image

**Comment by thevandie** [comment]
wait what

**Comment by thevandie** [comment]
filename
jackets
they aren't tho?

**Comment by thevandie** [comment]
yeah, I tested it in game, the clothes work.

**Comment by Kitsunemitsu** [comment]
Tested in game, merging

**Pull request merged**
