### PR TITLE
Adds new guns. Currently admin only

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
## About The Pull Request

Adds a few new guns. I had 20 minutes and nicole requested it.
I'm not making unique mags for this or I will go insane. I will add them in eventually

Sprites courtesy of Fortune 13/Fortuna 13/Lone Star.

## Why It's Good For The Game
It's a sprite and 4 lines of code, and more variety in the gamer gear admins can use.
Will eventually put the Sequoia in Remus facility

## Changelog
:cl:
add: Added new admin-only guns
/:cl:

### CODE REVIEW

**Review by retlaw34 — CHANGES_REQUESTED** [review]
The sequoia doesn't fit with any of the other revolvers right now. It looks like its based off the peacemaker variant of the detective's revovler but clockwork colored.

**Comment by Kitsunemitsu** [comment]
It was a specific request from Nicole, designated to be admin only. May or may not be used for Remus, but it's not a big deal if it's not.

**Comment by Kitsunemitsu** [comment]
It's supposed to be a gold-speckled revolver. Not the golden gun, just gold accents

**Comment by Kitsunemitsu** [comment]
The error is unrelated and fixed on master.

**Pull request merged**
