### PR TITLE
Adds Praetor

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
## About The Pull Request
Adds in a new megafauna, The Praetor.
Very simple, my first megafauna, I'm still working on it.
Also adds in 3 new ruins for various things

## Why It's Good For The Game
Honestly, we've always needed more megafauna for Rock, this bumps us up to 5 unique and 2 found else

## Changelog
:cl:
add: Added Praetor
add: Added Ruins for Praetor and clock defender
/:cl:

### CODE REVIEW

**Comment by bruhlookatthisdood** [comment]
no preview?
):<

**Comment by bruhlookatthisdood** [comment]
image

**Comment by Kitsunemitsu** [comment]
We'll see how this goes

**Comment by bruhlookatthisdood** [comment]
Are the things on the side of it's head horns?

**Comment by EgorDinamit** [comment]
Is this still being worked on..?
If so - giving it fireball is a REALLY bad idea.

**Comment by Kitsunemitsu** [comment]
I am honestly unsure on how to continue with this PR. I am trying to learn Megafauna Code.

**Comment by projectkepler-ru** [comment]
will use this in the map if it get done

**Comment by Kitsunemitsu** [comment]
No longer being worked on due to my inactivity

**Pull request closed without merging**
