### PR TITLE
TaliStation, Slime warden pet, new job; hobo and my beloved rainbow shirt

### PR DESCRIPTION
**Pull request by DaddyIssues98**
## About The Pull Request

Added a new map: TaliStation
lore: chimerastation arquitect got high in space drugs, make this mess and now we all have to deal with this.
real lore: Tali'Zorah is waifu. 

General imagen from the map:
the 'rona in the lungs

## Why It's Good For The Game
i like variety in maps, so i made maps.
if people like it we can keep it
if not we just remove it, is theory this was made to replace chimera but for now is a smaller map for less pop i will say 20-30 pop is good for this map instead of 66+ for chimera. 

**Note from Kirie:**
Some clothing is from Lonestar.

## Changelog
:cl:
add: added Talistation as a map
add: added rainbow slime shirt, is only in sprite and not in code.
/:cl:

### CODE REVIEW

**Comment by bruhlookatthisdood** [comment]
merging rn
I dont care if its broken or not done
im doing it and you cant stop me.

**Comment by bruhlookatthisdood** [comment]
for legal reasons the comment above is a joke

**Comment by Kalesonki** [comment]
Approved for merging.

**Comment by Kitsunemitsu** [comment]
Don't merge, I'm going to do some cleanup in a bit.

**Comment by Kitsunemitsu** [comment]
Merging later today. Everything easy to make modular is.

**Comment by DaddyIssues98** [comment]
self merging cause im a big boy

**Pull request merged**
