### PR TITLE
PART 1 OF ME HATING ALL OF YOU

### PR DESCRIPTION
**Pull request by DaddyIssues98**
## About The Pull Request

we dont need 3 files for chems, we dont need 10 files for weapons, WE DONT NEED THAT MANY FILES WEEEEEEEEEE

part 1 of 3
part 1: take all the multiple files and make it a single file for each type
part 2: do the same with icons
part 3: make the code preatty, organised it and shit, so it easy to find stuff.
## Why It's Good For The Game

IS NOT GOOD, IM LOSING MY FAITH IN THIS COMPANY, I SWEAR IF SOMEONE OFFER ME 1 COIN TO LEAVE THIS PLACE I WILL FUCKING DO IT

## Changelog
:cl:
/:cl:

### CODE REVIEW

**Comment by Kitsunemitsu** [comment]
Make sure you still have robbie's pistol in there.
I approve

**Comment by DaddyIssues98** [comment]
No idea how to fix the check

**Comment by DaddyIssues98** [comment]
well fuck it i dont knwo how to fix this

**Comment by DaddyIssues98** [comment]
hello owner of github here, is good merge or i will delete you

**Comment by BootlegBow** [comment]
probably fine

**Pull request merged**
