### PR TITLE
Romulus facility update v7

### PR DESCRIPTION
**Pull request by projectkepler-ru**
## About The Pull Request

everything MARSOC related :)
## Why It's Good For The Game
Romulus stuff

## Changelog
:cl:
add: Added MARSOC and a lot of MARSOC related item
/:cl:

### CODE REVIEW

**Comment by projectkepler-ru** [comment]
@Kitsunemitsu  this will be the last PR I make for bungalow for awhile. after this I'll downstream everything.
Will update stuff up if needed.

**Comment by thevandie** [comment]
Y'know, posting an image full of all the new added items in a room would be pretty helpful for... everyone... to know what's being added at a glance

**Comment by Kitsunemitsu** [comment]
Looks good, merging

**Comment by projectkepler-ru** [comment]
@thevandie  I am well aware. It's been extremely busy and I do not have the time to make that either. I rushed to get this out as soon as it was 'ready'  after fixing issues related to it

**Pull request merged**
