### PR TITLE
New jungle base. 

### PR DESCRIPTION
**Pull request by DaddyIssues98**
## About The Pull Request

 a different base for jungle, still not perfect but will time i will make it look better.

JUNGLE

## Why It's Good For The Game

re using the lavaland base for jungle is wrong
## Changelog
:cl:
tweak: jungle map
/:cl:

### CODE REVIEW

**Comment by Kitsunemitsu** [comment]
Gotta TM this for a bit.

**Comment by DaddyIssues98** [comment]
it got a little change in some parts, need to updatei magen but im lazy and its 2am.

**Comment by bruhlookatthisdood** [comment]
you tellin me the gulag prisoners can just walk into the mining base?

**Comment by DaddyIssues98** [comment]
> you tellin me the gulag prisoners can just walk into the mining base?

kinda? but there is doors that needs access so... also try to survive jungle as prisioner with a pickaxe

**Comment by Kitsunemitsu** [comment]
Merge when ready.

**Pull request merged**
