### PR TITLE
Attempting to put Frost Demonic Miner to Ice Moon Z-Level

### PR DESCRIPTION
**Pull request by BlackCat-055**
## About The Pull Request

Basically it turns out the Icemoon mining Z-Level doesn't have demonic frost miner and clockwork defender, both requires multi-z-levels, demonic frost miner because their stage is a two-parter map with their entrance at the icemoon surface and clockwork defender is set to be at the icemoon surface, which we don't have ours set the same, since we're ice moon underground.

So basically since I have no idea how to re-add the Icebox map but without the station, I'm doing this shitty fix instead! I hope this is okay Kizler.

I have to clarify while I did code it in, due to our random mining z level thing (and I dont know how to change it), I haven't been able to test it out actually, RNG hates me.

## Why It's Good For The Game

It fixes Icemoon a bit so it has more of the stuff it's supposed to have, so more content is always good

## why it's probably bad for the game

Technically this is a mining buff because if they kill the two re-added mobs and the wendigo, they can craft the super cool omega armor thingy loot. But I'm just gonna hope this doesn't explode on my face like a clown putting c4 on my apple pie.

## Changelog
:cl:
add: made new ruin for demonic frost miner
add: putteed that and clockie defender back into our mining icemoon z-level,  hopefully.
config: putted the demonic miner new ruin to the iceruinblacklist config since file said so

/:cl:

### CODE REVIEW

**Comment by Kitsunemitsu** [comment]
I need to add to this too, but it looks good

**Comment by Kitsunemitsu** [comment]
Linters a little fucked, fix and it's good to go

**Comment by bruhlookatthisdood** [comment]
do it work tho?

**Comment by Kitsunemitsu** [comment]
I'm going to have to finish this.
Should be good.

**Comment by Kitsunemitsu** [comment]
yeah fuck it, we're gonna merge.

**Pull request merged**
