### PR TITLE
New Contraband for Cargo Wardrobe

### PR DESCRIPTION
**Pull request by JRDead**
## About The Pull Request

Adds a minecraft steve clothing to the cargo wardrobe as a contraband item. It has the same stats as the regular mining jumpsuit.

Worn clothes sprites look like this:
image

In hand item sprite looks like this:
image

Steve clothing in Minecraft for comparison:
image

And this is how it looks in game:
This is me
image
This is Steve
image

## Why It's Good For The Game

I've been joking for a while about adding minecraft stuff to the game and I've been told it's cool so here I am.

## Changelog
:cl:
add: minecraft steve clothing
/:cl:

### CODE REVIEW

**Review by Kitsunemitsu — APPROVED** [review]

**Comment by Kitsunemitsu** [comment]
Waiting for someone else to merge

**Review by retlaw34 — COMMENTED** [review]
Sprites look pretty bland, although this might be intended, but its whatever

**Comment by JRDead** [comment]
> Sprites look pretty bland, although this might be intended, but its whatever

Totally intended, but even if i wanted to make them look better, Steve's clothes aren't too pretty anyway. I even used the same color palette from the regular minecraft Steve's skin.

**Review by retlaw34 — APPROVED** [review]
Okay by me then

**Comment by bruhlookatthisdood** [comment]
YES
THE HOPE FOR A MINECRAFT MAP GROWS
(i heard about it on the discord)

**Pull request merged**
