### PR TITLE
kepler station updoot v5 (722)

### PR DESCRIPTION
**Pull request by projectkepler-ru**
## About The Pull Request
fixing area generation issue while also tweaking in stuff

## Why It's Good For The Game
we made it more toleratable

## Changelog
:cl:
add: type 45 and type 40 sniper rifle, strong anti material rifle used by the ranger of the past. 
add: a new shotgun, the stopgap a four barrelled shotgun pistol that fit in your bag
add: a new melee weapon, the riot staff
add: more merc enemy type
add: Added new ruins
add: Added scavengers
add: weapon tier drop system
add: same with above, ammo tier drop system
add: Gatorade injector  and the bigger injector variant for blacksite, it heals nearly every type of damage.
add: Mercenary NPC having the chance to spawn an infected variant instead of their standard corpse
add: ammo box for certain type of ammo (this will hopefully become used for the next armylathe coming soon
balance: reduced the HK21 fire rate and made it spawn without mag
tweak: renamed majority of solgov npc to mercenary, excluding the scientist which will still be called Solgov Scientist
tweak: LMG and Shotgunner Mercs now have higher health and fire significantly faster
tweak: the sniper to have lower minimal firing distance so that they can shoot even if you're up close to them
tweak: the rocket launcher that sol gov get
tweak: the Hazmat being extremely oppressive, hopefully in the next test its less oppressive >_>
fix: genturf
fix: the game being too accessible to polish players but inaccessible to russian players.
/:cl:

### CODE REVIEW

**Comment by projectkepler-ru** [comment]
fuck how do i revert this

**Comment by projectkepler-ru** [comment]
once i finish up the ammo drop, I'll say it's ready

**Comment by Kitsunemitsu** [comment]
>125 Commits
Pack it in boys, new record.
I'm gonna look over sprites and merge

**Comment by Kitsunemitsu** [comment]
Changes approved. Good to go.

**Pull request merged**
