### PR TITLE
Adds Bamboo Sword, Chain of Captaincy. Removes Chain of Command from all maps.

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
## About The Pull Request
Adds the Bamboo sword and Chain of Captaincy, the last two planned captain weapons.
This brings our total up to a whopping 9.

The Bamboo sword is a Weapon that blocks bullets and normal attacks alike at 12% chance, but only does 10 damage. However, the belt starts with SEVEN of them, and the belt gives you a new martial art: Kenjitsu.
This martial art has two attacks (after a short windup): 
Palm Strike on disarm, which knocks people back and into walls
Body Slam on grab, which is like Leg Sweep, but worse, because it has a windup.
image
image

The other weapon is the Chain of Captaincy, a better chain of command that deals 10 damage, but has a 70(!) Wound damage bonus, -20 Armor penetration and a 2 square reach.
To avoid confusion, the Chain of Command has been removed from all maps in rotation.

## Why It's Good For The Game
I had a spare 3 hours, and really badly wanted to make these last two weapons. 
I feel like they both fill a niche.

## Changelog
:cl:
add: Added Bamboo bag and Chain of Captaincy
del: Removed Chain of Command for all maps in rotation.
/:cl:

### CODE REVIEW

**Comment by DaddyIssues98** [comment]
mmm captain giving weapons incomming

**Comment by Kitsunemitsu** [comment]
The weapons are not super great, to the point where you would only pick them for the 12 block chance, (2 of them 19% block chance, and it only has 10 force) are a bulky item cant fit in your bag, so if you coordinate to game with them its whatever, I will see how it goes and if it becomes a problem I will fix

**Comment by Kitsunemitsu** [comment]
Oh and the reason there's 7 of them is because it's cool, dont like it seethe

**Comment by thevandie** [comment]
now, parrying dagger where?

**Comment by Kitsunemitsu** [comment]
Out of the scope of this PR.
When I do the next gun PR I'll add it.

**Comment by DaddyIssues98** [comment]
i dont know why you remove the chain of command in the maps... and why in the same PR as adding a weapon?

**Comment by Kitsunemitsu** [comment]
They look the exact same.
I'll add it back into beacon-free maps.

**Comment by Kitsunemitsu** [comment]
Have to merge, Deployment software is screaming at me (I want to die)

**Pull request merged**
