### PR TITLE
Tramstation from TG

### PR DESCRIPTION
**Pull request by bruhlookatthisdood**
## About The Pull Request

its tram station from tg....
what else do you need to know?
https://github.com/tgstation/tgstation/pull/56509
image

## Why It's Good For The Game

me bored
what a code monkey does when bored, i port entire map.

## Changelog
:cl:
add: tram station, cope and seethe.
/:cl:

### CODE REVIEW

**Comment by Kalesonki** [comment]
this going to cure my cancer

**Comment by bruhlookatthisdood** [comment]
> As TG found out, [tgstation/tgstation#58340](https://github.com/tgstation/tgstation/pull/58340) needs porting before this can be fullmerged, other than that, I expect it to work fine, especially since Trams isn't in it's buggy release state

please.... its 104 files.. dont do this to me

**Comment by retlaw34** [comment]
> > As TG found out, [tgstation/tgstation#58340](https://github.com/tgstation/tgstation/pull/58340) needs porting before this can be fullmerged, other than that, I expect it to work fine, especially since Trams isn't in it's buggy release state
> 
> please.... its 104 files.. dont do this to me

The tram causes obscene lag if its trying to move a lot of things at once, plus, it helps lag everywhere else

**Comment by bruhlookatthisdood** [comment]
> > > As TG found out, [tgstation/tgstation#58340](https://github.com/tgstation/tgstation/pull/58340) needs porting before this can be fullmerged, other than that, I expect it to work fine, especially since Trams isn't in it's buggy release state
> > 
> > 
> > please.... its 104 files.. dont do this to me
> 
> The tram causes obscene lag if its trying to move a lot of things at once, plus, it helps lag everywhere else

i am going to make the most cursed port ever

**Comment by bruhlookatthisdood** [comment]
screaming and crying rn

**Comment by bruhlookatthisdood** [comment]
im too lazy to port the cross removal things
oh well, it worked in testing and everything smhsmhmsh.

**Comment by JohnFulpWillard** [comment]
do you want the branch or not

**Pull request closed without merging**
