### PR TITLE
Syndiestation

### PR DESCRIPTION
**Pull request by BlackCat-055**
I have no idea what Im doing
## About The Pull Request

I'm making a Syndicate Station because funny gun gun + Syndicate Gimmick, Im pulling this request now cause Ms. Jill said so to help with crunching the map size while it's WIP.

Only Perma-Brig, Sec and Bridge are done. Arrivals and Medsci are still being developed and everything else is pure space RN

Current Map of SyndieStation

SyndieStation

## Why It's Good For The Game

Because WE ARE OPRESSED BY NT PROPOGANDA! FOR TOO LONG WE HAVE BEEN FORCED TO PLAY NANOTRASEN STATIONS! BEING FED WITH MEDIA EQUIVALENT OF SLOP AND GRUB BY THE BNI! ONLY MORSELS OF SOLGOV AND SYNDICATE MAPS ARE GIVEN TO US! NO LONGER!!! COME BROTHERS AND SISTERS! LET US BREAK FREE OF OUR NT CORPORATE CHAINS AND BECOME ONE TOGETHER! A SYNDICATE! GLORY TO THE SYNDICATE!

Also cause funny station gimmick, may or may not fail horribly he hoo

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by thevandie** [comment]
**Baller**

**Comment by Kitsunemitsu** [comment]
I am taking this project over right now.

**Comment by Kitsunemitsu** [comment]
Why does this require host approval again?

**Comment by bruhlookatthisdood** [comment]
is this still even being worked on?

**Comment by Kitsunemitsu** [comment]
Yes, kinda

**Comment by Kitsunemitsu** [comment]
New PR merged about syndiestation.
Thank you for the help Jenny!

**Pull request closed without merging**
