### PR TITLE
Adds genpop from yog

### PR DESCRIPTION
**Pull request by bruhlookatthisdood**
## About The Pull Request

Ports Genpop from yogstation. 
image

As a demonstration, I will brig Brodie Brinigh for Theft and Trespass. We'll input the details, and it sets the time.

image

Hitting "Finalize ID" prints out the completed prisoner ID, and begins tracking our time in the brig. It also prints a piece of paperwork to be filed by the warden (or thrown away). The ID looks something like this:

image

Next, we'll need to strip our prisoner. Find an un-assigned GenPop locker, open it, and strip the prisoner of everything but his jumpsuit (ID included)

image

To seal the locker, slide the ID over the locker and it locks shut and assigns itself to that ID. It can be opened by the prisoner later once the brig time is up. Then just put the prisoner into a cell with the temporary ID, and you are good to go! The system automatically updates arrest status and security records.

image

Once released, special access is added to the prisoner ID card that enables them to walk out of turnstiles, so they can collect their stuff and let themselves out. 

image

## Why It's Good For The Game

More stuff for security, easier to give brig sentances.

## Changelog
:cl:
add: New security genpop system.
/:cl:

### CODE REVIEW

**Comment by DaddyIssues98** [comment]
i dont know what this it is, it confusme and make me want to run. we need to test merge it.

**Comment by StoneMason** [comment]
This shit seems based as fuck.

**Comment by bruhlookatthisdood** [comment]
errors? what are those?

**Comment by bruhlookatthisdood** [comment]
going to work on other things, will come back to this later

**Pull request closed without merging**
