### PR TITLE
Framework for New Antagonist: BNI Black Ops Agent & NT-Exclusive Uplink

### PR DESCRIPTION
**Pull request by BlackCat-055**
## About The Pull Request

So. I'll be blunt, this isn't a ready-made new Antagonist, it's not done yet, but Ma'am wanted to have an NT-exclusive uplink and to do that I had to make a framework where said uplink would be used, of course  I forgot Internal Affairs Agent game mode existed but I had enough stuff that might as well kept it.

### Framework for Antag: BNI Black Ops Agent
unknown (1)

BNI Black Ops Agent is a new type of traitor that's similar to IAA wherein they're contracted by Nanotrasen, more specifically their Black Ops division, The Bureau of Nanotrasen Intelligience, I won't say what they'll inteneded to be as I feel that would make false promises, but  for the foreseable future, their objectives will be a bit similar to normal antagonists but done differently as to not be "Antagonistic" to Nanotrasen (they're employed by them of course), Assassinations will target antagonists, martry and hijack is a full no go, but however I'll attempt to give them objectives that'll ensure they're not simply another ally to the Station, we can't just a friendly tot for sec to ally with. They'll likely have buggings and maybe "Securing" of certain high-risk items, maybe testing experimental stuff, essentially porting some objectives from the Progression Traitor PR TG has, they'll also capture Heads (except Commodore and Marshall) and bring them along the escape pod due to a lore-base flavoring that they were corrupt and BNI is handling them off the grid.

But for now, they're just a traitor with a unique uplink and different code-phrase system, which I'll explain below

### Nanotrasen-Based Code Phrases
image

I essentially made it so NT Black Ops have their entirely own set of code words completely different from the Syndicate, so they may identify other BNI Agents, that way, they can't mistakenly talk to traitors and assume each other are allies when they are not.

Pretty simple, just has a entirely different set of code words and such from the normal traitors, but pulls from the same words. IAA don't get it because simply put their goal is killing each other, they kinda already identify one another with the tracker implant

### NT-Exclusive Uplink
unknown
unknown

unknown

unknown

Ma'am or the Headcoder decided that it would be better if Internal Affairs Agent and now BNI Black Ops had their own uplink separate from the norma Traitors, I've helped place the frame work for it as it's planned the background will have the NT logo, I just don't know how to manipulate TGUI code. But the framework is somewhat there. I already have placed some NT-exclusive items related in the Uplink as examples, may put more in the future.

## Why It's Good For The Game

Variety, a new antagonist is always good and one that actually is both a neutral force, one that can attack other antagonists and the station would give a bit of conflict in it. Ma'am also wanetd an NT-Exclusive Uplink so I made this PR as she requested, just with extra stuff I made as a side

## Problems this PR currently has

- BNI Black Ops currently are set to Syndicate faction, not good, I'll figure out how to add Deathsquad or the NT faction var later
- BNI Black Ops currently get two Uplinks upon becoming said antag, I don't know why that happens, but the latest uplink passcode is the one that works among the two and the Agent gets 60 TC due to this, gonna figure this out
- The NT-equivalent of the Syndicate Radio Encryption key had a few issues, in concept it's supposed to act like said Syndie key but instead of syndie coms, it's supposed to have CentCom comms, but the "hear but not speak to the departmental" comms can't work since aparrently that thing is tied to the Syndie comms and I have no idea how to change that, so for now, BNI agents have a upper-hand against Traitors as they have access to both the CC comms and Syndie comms to have the "listen but not speak in all departmental comms", so BNI agents have their own comms to talk to and can peek at their enemies' comms but the Traitors can't

## To Do

- [x] Give BNI agents their own brand of antags
- [x] Fix the Faction issue
- [x] Fix the Double Uplink issue
- [x] fix the radio issue
- [x] I dunno what else

## Changelog
:cl:
add: Framework for a new Antag
add: An NT-Exclusive Uplink
add: Added NT-algined Code Phrases
fix: fixed the duplication glitch
fix: fixed the other tot types having access to the NT-exxclusive items
fix: Fixed the radio problem
add: made BNI Blackops be recognized as part of the BNI (have the Deathsquad faction var)
balance: removed Pulse items from uplink

code: copy-pasted Syndie code phrases code and edited to make it be NT
code: edited SOCOm to be Supressable
/:cl:

### CODE REVIEW

**Comment by bruhlookatthisdood** [comment]
you added pulse rifle and pistols for about 20 tc
i can buy 3 pulse rifles?
:trollface:

**Comment by BlackCat-055** [comment]
> you added pulse rifle and pistols for about 20 tc i can buy 3 pulse rifles? :trollface:

You're supposed to have only 30 TC, just bugged out currently
But you're not really supposed to murderbone with this, as the planned objectives will be more spy-like in nature.

**Comment by Kitsunemitsu** [comment]
I took this up.
This is not a gamemode to be normally used for right now.
We will eventually turn this into a midround.
As a midround, it works.
Merging.

**Comment by bruhlookatthisdood** [comment]
why do normal traitors get a "stolen syndicate contractor baton"

**Pull request merged**
