### PR TITLE
Minor Sec Stat Change

### PR DESCRIPTION
**Pull request by thevandie**
## About The Pull Request

Gives all 3 navy formal jackets proper armor and the ability to hold weapons. Also makes the det coats viable as they had statistically less armor than the det vest. (Tested on local, all works perfectly fine)

## Why It's Good For The Game

Making the security drip options usable is a very good idea.

## Changelog
:cl:
tweak: buffs the det armor to be on-par with the rest of the sec gear.
add: Armor stats for the sec formal jackets
/:cl:

### CODE REVIEW

**Comment by thevandie** [comment]
dont merge yet I forgot to add a thing kirie asked for

**Review by bruhlookatthisdood — CHANGES_REQUESTED** [review]
As you changed the obj paths you also need to change them on the maps where they spawn.
Do that to fix the errors.

**Comment by DaddyIssues98** [comment]
fermistation and meta broke, pleace edit the maps to fix it.

**Comment by thevandie** [comment]
AHHHHHHHHHHH

**Comment by thevandie** [comment]
it's fixed

**Review by bruhlookatthisdood — APPROVED** [review]

**Pull request merged**
