### PR TITLE
Xeno nerfs (Again)

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
## About The Pull Request

Also includes one line fix for Cargo tech

I am supposed to be on break and still had to do this.
Fucking hate Xenos. I literally would remove them aside from the funky gamemodes but Improve not remov

## Why It's Good For The Game
I'm sick of Xenos, honestly.

## Changelog
:cl:
balance: rebalanced neurtoxin
balance: rebalanced tackle
/:cl:

### CODE REVIEW

**Review by retlaw34 — DISMISSED** [review]
If improving is by removing then, remove it

**Comment by DaddyIssues98** [comment]
gooddamit kirie dont put nerfs and fixes in the same PR

**Comment by Kitsunemitsu** [comment]
It's a one value, Critical fix for cargo tech and I really dont want to open another PR unless this is closed.

**Comment by Kitsunemitsu** [comment]
Rework coming soon, going to merge for now.

**Pull request merged**
