### PR TITLE
Adds jungle techcult ruin.

### PR DESCRIPTION
**Pull request by bruhlookatthisdood**
## About The Pull Request

Read title

## Why It's Good For The Game

More jungle ruins.

## Changelog
:cl:
add: Added techcult ruin to jungle planet.
/:cl:

### CODE REVIEW

**Comment by bruhlookatthisdood** [comment]
planning on... one in space maybe??!/1/!?/1?!/!?1

**Comment by Kitsunemitsu** [comment]
Alright, I don't think you've ever played Remus.
Jungle planet is BRUTAL.
ABSOLUTELY FUCKING BRUTAL.
I will be adding laser guns to this map before testing.

**Comment by bruhlookatthisdood** [comment]
yeah ive never played on the jungle planet before, thought it was just lavaland but with easier to beat creatures.

**Comment by Kitsunemitsu** [comment]
They die to guns, yeah.
But they have ranged attacks that break your legs

**Comment by bruhlookatthisdood** [comment]
Doesn't the leader spawn with a big energy rifle though?

**Comment by EgorDinamit** [comment]
> Doesn't the leader spawn with a big energy rifle though?

They do, and it was meant to be tech cult unique. I don't remember if Kirie added it to the normal station loadouts, but if so - it sucks.
If jungle station is that bad just give them more weapons to be on par with what miners have there.

**Pull request merged**
