### PR TITLE
Ports slings from yog

### PR DESCRIPTION
**Pull request by bruhlookatthisdood**
## About The Pull Request
Ports slings from yogstation pull request #2323

## Why It's Good For The Game

New antag, new me.

## Changelog
:cl:
add: VYSHA NERADA YEKHEZET U'RUU!!
/:cl:

### CODE REVIEW

**Comment by bruhlookatthisdood** [comment]
waiting for kirie to fix hud folder

**Comment by bruhlookatthisdood** [comment]
due to issues with casio station, I will wait utnil kirie approves

**Comment by bruhlookatthisdood** [comment]
local head coder once again saves my life

**Comment by bruhlookatthisdood** [comment]
i will need to balance this, for now its a do not merge but feel free to test merge kirie.

**Comment by bruhlookatthisdood** [comment]
i cant balence them
please
someone do it for me so i dont have to

**Comment by Kitsunemitsu** [comment]
Honestly, I'm ok with them being on the weak side.
I'm approving this, need another developer to merge.

**Pull request merged**
