### PR TITLE
Towerstation

### PR DESCRIPTION
**Pull request by retlaw34**
## About The Pull Request
You and I know exactly what this is

## Changelog
:cl:
add: towerstation
/:cl:

### CODE REVIEW

**Review by EgorDinamit — APPROVED** [review]
9/10, not enough z-levels.

**Comment by retlaw34** [comment]
> 9/10, not enough z-levels.

Wouldn't it be 10/12

**Comment by retlaw34** [comment]
I hope this was TMed

**Comment by bruhlookatthisdood** [comment]
reopen it
make it a official map
now
this is a threat

**Comment by Kitsunemitsu** [comment]
Opening to TM.

**Review by Kitsunemitsu — APPROVED** [review]

**Comment by Kitsunemitsu** [comment]
So, I am actually seriously considering keeping this merged.

I have only two issues:
Some airlocks that should cycle don't.
Chemistry needs an outside door.

**Comment by retlaw34** [comment]
> So, I am actually seriously considering keeping this merged.
> 
> I have only two issues: Some airlocks that should cycle don't. Chemistry needs an outside door.

There are some very good  reasons why this wasn't merged in the first place 
1. It was originally made as a joke, I refurbished as a joke
2. MultiZ on tgcode is painful
3. No maintenance on the entire map
4. I would actually maxcap myself than have this merged

**Comment by bruhlookatthisdood** [comment]
image

**Pull request closed without merging**
