### PR TITLE
Mining Overhaul and Asteroid Mining Field

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
## About The Pull Request
Overview: Adds new weather, replaces rockplanet mobs, adds in a new mining planet and removes the chaos marine from space.

Adds in Asteroid Field mining, and gets that damn Chaos Marine out of space.
Miners would rush it every round, which is annoying but understandable.
This makes it a lot harder to get. Now it's not always in the pool.
The map itself is about 3x taller than a normal SS13 mining planet map, meaning that you end up having to go further and further for materials. The only real boss is the chaos marine.

The mining base for this map is on a space ship, with space for 5-9 crew, including command staff quarters (for the secretary), 3 mining bunks, a full infirmary with (empty) chemical storage

Engineering is equipped with a TEG, RPED and everything it needs.
Sending 3-4 station members here isn't the worst idea. Let's see how this works out <3

This also overhauls the Voidstorm weather, buffs the Icestorm one, and makes the Acid rain weather actually work.
Also adds in Diamond dust and Space Wind weathers.
Reworks the rock mobs to all be resistant to the weather there, the same cannot be said about the peeps in the ruins.

To Do: 
[x]Add ruins
[x]Add more space mobs
[ ]Remove the chaos marine from space

## Why It's Good For The Game
Chaos Marine is not always available, and more mining planets is always a good thing

Mining Beret Preview
image

Base Preview
image

## Changelog
:cl:
add: Added Asteroid Mining
add: Added new mining berets
add: Added Space Wind weather, which knocks you on your ass
add: Added Diamond dust weather, which tears you to shreds
del: Removed chaos marine from space
tweak: Changed the list of mining mobs on rockplanet to fit a theme better
tweak: Megafauna are no longer laser resistance. Fuck you.
fix: fixed Mining and grey berets
fix: fixed Acid rain, gave it better sprites.
fix: fixed Snowstorm not actually doing anything
fix: fixed Void Storm so it actually works on Rock and Asteroid
fix: Some un-atomized shitcode rockplanet base fixes
/:cl:

### CODE REVIEW

**Comment by bruhlookatthisdood** [comment]
we are slowly turning into NSV o

**Comment by bruhlookatthisdood** [comment]
Does this replace normal mining? If so what happens to the other megafauna?

**Comment by Kitsunemitsu** [comment]
Does not replace normal mining.
It's another mining planet like jungle.

The only thing it removes is the Chaos marine from space.

**Comment by bruhlookatthisdood** [comment]
I can imagine the miners getting ready to see what planeit is and end up on a ship

**Comment by bruhlookatthisdood** [comment]
can there be jetpacks?

**Comment by Kitsunemitsu** [comment]
Jetpacks Added.

**Pull request merged**
