### PR TITLE
[PORT] security uniform resprites

### PR DESCRIPTION
**Pull request by 1393F**
## About The Pull Request
https://github.com/tgstation/tgstation/pull/63769
https://github.com/tgstation/tgstation/pull/64323
https://github.com/tgstation/tgstation/pull/60414 (HoS formal jacket only)not currently obtainable

## Why It's Good For The Game
some nice looking sprites?

## Changelog
:cl:
imageadd: New sprites for some security uniforms, mostly HoS
tweak: Adjusted security jumpsuits/skirts no longer cover the chest
/:cl:

### CODE REVIEW

**Comment by bruhlookatthisdood** [comment]
oh my god why does the warden have mega honkers now

**Comment by Kitsunemitsu** [comment]
HOS Formal coat 
1) is something we already use elsewhere
2) Doesn't really fit the theme of the HOS
3) adds to the extremely large amount of HOS clothing we already have

**Comment by 1393F** [comment]
> HOS Formal coat
> 
>     1. is something we already use elsewhere
> 
>     2. Doesn't really fit the theme of the HOS
> 
>     3. adds to the extremely large amount of HOS clothing we already have

1. where
2. how does it not fit the theme of HoS? They already have formal uniforms but not a coat
3. and we have alot of captain clothing, so what?

**Comment by DaddyIssues98** [comment]
i like them.

**Comment by thevandie** [comment]
> > HOS Formal coat
> > ```
> > 1. is something we already use elsewhere
> > 
> > 2. Doesn't really fit the theme of the HOS
> > 
> > 3. adds to the extremely large amount of HOS clothing we already have
> > ```
> 
> 1. where
> 2. how does it not fit the theme of HoS? They already have formal uniform but not a coat
> 3. and we have alot of captain clothing, so what?

1) provost coat.
2) it doesn't fit because the HoS probably shouldn't have a super officer-y coat
3) probably because it IS captain and officer clothing.

**Comment by thevandie** [comment]
but cap isn't the only one with alt clothing? HoS already has a bunch of alt clothing, hell, if anything give him a proper vest (not carapace because loooore). Im sick of coats at this point.

**Comment by 1393F** [comment]
> but cap isn't the only one with alt clothing? HoS already has a bunch of alt clothing, hell, if anything give him a proper vest (not carapace because loooore). Im sick of coats at this point.

while I understand what you mean, what type of vest would he even get?(I often just grab a standard seccie vest from the lockers)

**Comment by Kitsunemitsu** [comment]
Good to merge.

Spoke about this in the discord, adding the hos formal coat later (We already have the sprites)

**Pull request merged**
