### PR TITLE
Fixes techcult ruin computers.

### PR DESCRIPTION
**Pull request by bruhlookatthisdood**
## About The Pull Request

Read title
Before: 
image

After: 
image

## Why It's Good For The Game

Its a fix for the icons.

## Changelog
:cl:
fix: Fixed techcult ruins computer frame icon being off
/:cl:

### CODE REVIEW

**Comment by DaddyIssues98** [comment]
now big fan of techpriest having a RnD console, so other devs need to merge this

**Comment by retlaw34** [comment]
Requesting Egor since they made the ruin

**Comment by EgorDinamit** [comment]
Tech cult was never meant to have a round-start RnD console for balance reasons.
They are **meant** to travel to the station and interact with the crew if they want one.

**Review by EgorDinamit — CHANGES_REQUESTED** [review]
Tech cult was never meant to have a round-start RnD console for balance reasons.
They are meant to travel to the station and interact with the crew if they want one.

**Comment by bruhlookatthisdood** [comment]
Ill just make it so it only fixed the computer then.

**Review by EgorDinamit — APPROVED** [review]
Looks good.

**Pull request merged**
