### PR TITLE
m90 changes (that are objectively better)

### PR DESCRIPTION
**Pull request by thevandie**
## About The Pull Request

Changes the sprites of the M90GL and the M90A to 1) make the new M90 sprite less atrocious and to 2) to the make the M90A up to speed with the new M90 sprites.
(Tested on local, worked good)

## Why It's Good For The Game

The old new M90 sprite was... atrocious. Mostly because it's colorscheme clashed with literally everything around it.

## Changelog
:cl:
add: M90A Carbine sprite change
add: M90 GL sprite change
add: New magazine and empty sprites for the M90A because it was still using the old ones.
/:cl:

M90s

### CODE REVIEW

**Comment by DaddyIssues98** [comment]
there is a special thing in changelog to use when change sprites and you used the "add" one. damm i wanna :hurt: you

**Comment by thevandie** [comment]
I added something? thought I just replaced everything (by pasting them from a different file) unless the pasting is what you mean in which case FUCK

**Comment by thevandie** [comment]
oh wait changelog, nvm

**Review by retlaw34 — APPROVED** [review]
> Mostly because it's colorscheme clashed with literally everything around it.
 

Now you get it

**Comment by thevandie** [comment]
heh? that's what I always said, bad colorscheme.

**Pull request merged**
