### PR TITLE
Casiostation Armory Improvement

### PR DESCRIPTION
**Pull request by thevandie**
## About The Pull Request

Adds more guns to the Casio Armory, proper guns. This is a military station, it makes sense for the armory to be filled with weapons of expected quality. This includes:
3 Tactical Eguns
2 L704 Laser Rifles
1 L504 (Prototype) Laser Rifle
3 Riot Shotguns
Shotgun Shells
And Nonlethal Grenades

Tested on Local, works great.

## Why It's Good For The Game

The Casio armory was... very, very underequipped. The whole crafting your own guns gimmick was... ok? but it left the station horribly undefended, no lethals in sight. This is a military station, our main military station, it makes zero sense for there to be ZERO lethal weapons.

## Changelog
:cl:
add: 3 Lasguns
add: 3 Tac-Eguns
add: 3 Shotguns
add: Shotgun Shells
add: Grenades
add: Handout Window
add: moved the disabler kits to a locker outside
add: Lieutenant NUMB NUTS!
add: Charlie. Poor Charles...
tweak: Tac-eguns are no longer old tasers
/:cl:

casioarmory

### CODE REVIEW

**Comment by Kitsunemitsu** [comment]
Tac Eguns literally have oldtaser

**Comment by thevandie** [comment]
hm. that does need changed anyway.

**Comment by thevandie** [comment]
fixed

**Comment by BlackCat-055** [comment]
Im merging it, blame any problems on lil ol' me~

**Pull request merged**
